package:
  name: conda-cookie
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - attrdict
    - requests
    - gitpython
  run:
    - python

test:
  imports:
    - conda-cookie
  requires:
    - pytest
    - pytest-spec
    - pytest-cov
  commands:
    py.test --cov=conda-cookie tests/
