package:
  name: {{ name }}
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - {{ name }}
  requires:
    - pytest
    - pytest-spec
    - pytest-cov
  commands:
    py.test --cov={{ name }} tests/
